blueprint:
  name: alarm
  description: alarm_description
  icon: "M6,6.9L3.87,4.78L5.28,3.37L7.4,5.5L6,6.9M13,1V4H11V1H13M20.13,4.78L18,6.9L16.6,5.5L18.72,3.37L20.13,4.78M4.5,10.5V12.5H1.5V10.5H4.5M19.5,10.5H22.5V12.5H19.5V10.5M6,20H18A2,2 0 0,1 20,22H4A2,2 0 0,1 6,20M12,5A6,6 0 0,1 18,11V19H6V11A6,6 0 0,1 12,5Z"
  group: alarm
  domain: automation
  input:
    trigger_device:
      name: alarm
      description: alarm_automation_description
      selector:
        entity:
          domain: alarm_control_panel
    target_device:
      name: target_device_name
      description: target_device_description
      default: {}
      selector:
        target:
          entity:
            domain: switch
    notification_device:
      name: notification_device_name
      description: notification_device_description
      selector:
        device:
          integration: mobile_app
    notification_text:
      name: notification_text_name
      description: notification_text_description
      default: ""
      selector:
        text:
    # message_telegram:
    #   name: Telegram message
    #   description: Text of the notificiation
    #   selector:
    #     text:
    # chat_id:
    #   name: Telegram user
    #   description: Chat id of the telegram user to receive notifications
    #   selector:
    #     text:

trigger:
  - platform: state
    entity_id: !input trigger_device

condition:
  - condition: template
    value_template: "{{ trigger.to_state.state == 'triggered' }}"

action:
  - service: homeassistant.turn_on
    target: !input target_device
  - device_id: !input notification_device
    domain: mobile_app
    type: notify
    message: !input notification_text
mode: single
