blueprint:
  name: motion_activation
  description: motion_activation_description
  icon: "M10,0.2C9,0.2 8.2,1 8.2,2C8.2,3 9,3.8 10,3.8C11,3.8 11.8,3 11.8,2C11.8,1 11,0.2 10,0.2M15.67,1A7.33,7.33 0 0,0 23,8.33V7A6,6 0 0,1 17,1H15.67M18.33,1C18.33,3.58 20.42,5.67 23,5.67V4.33C21.16,4.33 19.67,2.84 19.67,1H18.33M21,1A2,2 0 0,0 23,3V1H21M7.92,4.03C7.75,4.03 7.58,4.06 7.42,4.11L2,5.8V11H3.8V7.33L5.91,6.67L2,22H3.8L6.67,13.89L9,17V22H10.8V15.59L8.31,11.05L9.04,8.18L10.12,10H15V8.2H11.38L9.38,4.87C9.08,4.37 8.54,4.03 7.92,4.03Z"
  group: motion
  domain: automation
  input:
    motion_entity:
      name: motion_sensor_name
      description: motion_sensor_description
      selector:
        entity:
          domain: binary_sensor
    switch_target:
      name: switch_target_name
      description: device_action_switch_description
      default: {}
      selector:
        target:
          entity:
            domain: switch
    light_target:
      name: light_target_name
      description: device_action_light_description
      default: {}
      selector:
        target:
          entity:
            domain: light
    no_motion_wait:
      name: action_time
      description: action_time_description
      default: 1
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: minutes

# If motion is detected within the delay,
# we restart the script.
mode: restart
max_exceeded: silent

variables:
  no_motion_wait: !input no_motion_wait

trigger:
  platform: state
  entity_id: !input motion_entity
  from: "off"
  to: "on"

action:
  - alias: "Turn on the light"
    service: homeassistant.turn_on
    target: !input light_target
  - alias: "Turn on the switch"
    service: homeassistant.turn_on
    target: !input switch_target
  - alias: "Wait until there is no motion from device"
    wait_for_trigger:
      platform: state
      entity_id: !input motion_entity
      from: "on"
      to: "off"
  - alias: "Wait the number of minutes that has been set"
    delay: "{{ (no_motion_wait | int) * 60  }}"
  - alias: "Turn on the light"
    service: homeassistant.turn_off
    target: !input light_target
  - alias: "Turn on the switch"
    service: homeassistant.turn_off
    target: !input switch_target
