Luxuoso:
  # Raquel:
  raquel-white: "#FFFFFF"
  raquel-grey-1: "#D8D8D8"
  raquel-grey-2: "#929292"
  raquel-dark-1: "#2D2D30"
  raquel-dark-2: "#101012"
  raquel-dark-3: "#494D4F"
  raquel-gold: "#FFC876"

  # main colors
  primary-color: var(--raquel-dark-3)
  accent-color: var(--raquel-gold)
  # Backgrounds
  primary-background-color: var(--raquel-dark-2)
  secondary-background-color: var(--raquel-grey-1)
  card-background-color: var(--raquel-dark-3)
  header-card-picker-background: var(--raquel-grey-2)
  # Text
  primary-text-color: var(--raquel-white)
  secondary-text-color: var(--raquel-grey-1)
  disabled-text-color: rgba(184, 190, 199, 0.4)
  app-header-text-color: var(--raquel-white)
  header-text-color: var(--raquel-white)
  # Switches
  switch-checked-button-color: var(--accent-color)
  switch-checked-track-color: var(--accent-color)
  switch-unchecked-button-color: var(--raquel-dark-3)
  switch-unchecked-track-color: var(--raquel-grey-2)
  # Other colors
  divider-color: rgba(225, 225, 225, .20)
  mdc-ripple-color: "#AAAAAA"



  # novas variaveis
  background-color-rgb: rgb(73,77,79)
  background-color-rgb-hover: rgba(255,200,118,0.3)
  ha-fab-text-color: var(--raquel-dark-2)
  paper-slider-disabled-knob-color: var(--accent-color)
  slider-color: var(--accent-color)
  app-header-edit-background-color: var(--raquel-gold)
  app-header-selection-bar-color: var(--raquel-white)
  form-border: var(--raquel-claro)
  divider-editor: rgba(255, 255, 255, 0.3)
  sidebar-text-color-select: var(--raquel-gold)
  sidebar-icon-color-select: var(--raquel-gold)
  app-header-edit-text-color: var(--raquel-claro)

  # States and Badges
  state-icon-color: var(--raquel-grey-1)
  state-icon-active-color: var(--raquel-gold)

  input-idle-line-color: rgba(255, 255, 255, 0.42)
  input-hover-line-color: rgba(255, 255, 255, 0.87)
  input-disabled-line-color: rgba(255, 255, 255, 0.06)
  input-outlined-idle-border-color: rgba(255, 255, 255, 0.38)
  input-outlined-hover-border-color: rgba(255, 255, 255, 0.87)
  input-outlined-disabled-border-color: rgba(255, 255, 255, 0.06)
  input-fill-color: var(--raquel-dark-3)
  input-disabled-fill-color: rgba(255, 255, 255, 0.02)
  input-ink-color: rgba(255, 255, 255, 0.87)
  input-label-ink-color: var(--raquel-grey-2)
  input-disabled-ink-color: rgba(255, 255, 255, 0.37)
  input-dropdown-icon-color: rgba(255, 255, 255, 0.54)

  codemirror-keyword: "#C792EA"
  codemirror-operator: "#89DDFF"
  codemirror-variable: "#f07178"
  codemirror-variable-2: "#EEFFFF"
  codemirror-variable-3: "#DECB6B"
  codemirror-builtin: "#FFCB6B"
  codemirror-atom: "#F78C6C"
  codemirror-number: "#FF5370"
  codemirror-def: "#82AAFF"
  codemirror-string: "#C3E88D"
  codemirror-string-2: "#f07178"
  codemirror-comment: "#545454"
  codemirror-tag: "#FF5370"
  codemirror-meta: "#FFCB6B"
  codemirror-attribute: "#C792EA"
  codemirror-property: "#C792EA"
  codemirror-qualifier: "#DECB6B"
  codemirror-type: "#DECB6B"
  energy-grid-return-color: "#a280db"
  mdc-switch__pointer_events: auto


  state-icon-unavailable-color: var(--raquel-grey-2)
  state-icon-error-color: var(--error-state-color)
  state-unavailable-color:
    var(--state-icon-unavailable-color)
  sidebar-text-color: var(--secondary-text-color)
  sidebar-background-color: var(--card-background-color)
  sidebar-selected-text-color: var(--sidebar-text-color-select)
  sidebar-selected-icon-color: var(--sidebar-icon-color-select)
  sidebar-icon-color: var(--secondary-text-color)
  switch-checked-color: var(--primary-text-color)
  # switch-checked-button-color:
  #   var(--switch-checked-color var(--primary-background-color))
  # switch-checked-track-color: var(--switch-checked-color #000000)
  # switch-unchecked-button-color:
  #   var(--switch-unchecked-color var(--primary-background-color))
  # switch-unchecked-track-color: var(--switch-unchecked-color #000000)
  slider-secondary-color: var(--light-primary-color)
  slider-track-color: var(--scrollbar-thumb-color)
  label-badge-background-color: var(--card-background-color)
  label-badge-text-color: rgba(var(--rgb-primary-text-color) 0.8)
  paper-listbox-background-color: var(--card-background-color)
  paper-item-icon-color: var(--state-icon-color)
  paper-item-icon-active-color: var(--state-icon-active-color)
  table-row-background-color: var(--primary-background-color)
  table-row-alternative-background-color: var(--secondary-background-color)
  paper-slider-knob-color: var(--slider-color)
  paper-slider-knob-start-color: var(--slider-color)
  paper-slider-pin-color: var(--slider-color)
  paper-slider-pin-start-color: var(--slider-color)
  paper-slider-active-color: var(--slider-color)
  paper-slider-secondary-color: var(--slider-secondary-color)
  paper-slider-container-color: var(--slider-track-color)
  data-table-background-color: var(--card-background-color)
  markdown-code-background-color: var(--primary-background-color)

  # // https://github.com/material-components/material-web/blob/master/docs/theming.md
  mdc-theme-primary: var(--accent-color)
  mdc-theme-secondary: var(--accent-color)
  mdc-theme-background: var(--input-fill-color)
  mdc-theme-surface: var(--card-background-color)
  mdc-theme-on-primary: var(--primary-text-color)
  mdc-theme-on-secondary: var(--app-header-text-color)
  mdc-theme-on-surface: var(--primary-text-color)
  mdc-theme-text-disabled-on-light: var(--disabled-text-color)
  mdc-theme-text-primary-on-background: var(--primary-text-color)
  mdc-theme-text-secondary-on-background: var(--secondary-text-color)
  mdc-theme-text-hint-on-background: var(--secondary-text-color)
  mdc-theme-text-icon-on-background: var(--secondary-text-color)
  mdc-theme-error: var(--error-color)
  app-header-background-color: var(--primary-color)
  mdc-checkbox-unchecked-color: var(--primary-text-color)
  mdc-checkbox-disabled-color: var(--disabled-text-color)
  mdc-radio-unchecked-color: rgba(var(--rgb-primary-text-color), 0.54)
  mdc-radio-disabled-color: var(--disabled-text-color)
  mdc-tab-text-label-color-default: var(--primary-text-color)
  mdc-button-disabled-ink-color: var(--disabled-text-color)
  mdc-button-outline-color: var(--divider-color)
  mdc-dialog-scroll-divider-color: var(--divider-color)

  mdc-text-field-idle-line-color: var(--input-idle-line-color)
  mdc-text-field-hover-line-color: var(--input-hover-line-color)
  mdc-text-field-disabled-line-color: var(--input-disabled-line-color)
  mdc-text-field-outlined-idle-border-color:
    var(--input-outlined-idle-border-color)
  mdc-text-field-outlined-hover-border-color:
    var(--input-outlined-hover-border-color)
  mdc-text-field-outlined-disabled-border-color:
    var(--input-outlined-disabled-border-color)
  mdc-text-field-fill-color: var(--input-fill-color)
  mdc-text-field-disabled-fill-color: var(--input-disabled-fill-color)
  mdc-text-field-ink-color: var(--input-ink-color)
  mdc-text-field-label-ink-color: var(--input-label-ink-color)
  mdc-text-field-disabled-ink-color: var(--input-disabled-ink-color)

  mdc-select-idle-line-color: var(--input-idle-line-color)
  mdc-select-hover-line-color: var(--input-hover-line-color)
  mdc-select-outlined-idle-border-color:
    var(--input-outlined-idle-border-color)
  mdc-select-outlined-hover-border-color:
    var(--input-outlined-hover-border-color)
  mdc-select-outlined-disabled-border-color:
    var(--input-outlined-disabled-border-color)
  mdc-select-fill-color: var(--input-fill-color)
  mdc-select-disabled-fill-color: var(--input-disabled-fill-color)
  mdc-select-ink-color: var(--input-ink-color)
  mdc-select-label-ink-color: var(--input-label-ink-color)
  mdc-select-disabled-ink-color: var(--input-disabled-ink-color)
  mdc-select-dropdown-icon-color: var(--input-dropdown-icon-color)
  mdc-select-disabled-dropdown-icon-color: var(--input-disabled-ink-color)

  chip-background-color: rgba(var(--rgb-primary-text-color), 0.15)
  # // Vaadin
  material-body-text-color: var(--primary-text-color)
  material-background-color: var(--card-background-color)
  material-secondary-background-color: var(--secondary-background-color)
  material-secondary-text-color: var(--secondary-text-color)
